build:
	gcc -g -o bin/DuckHunt.out \
	src/DuckHunt.c  src/funciones.c  \
	-lcsfml-system -lcsfml-graphics -lcsfml-window -lcsfml-audio \
	-L /usr/lib/x86_64-linux-gnu/ \
	

run:
	bin/DuckHunt.out

clean:
	rm -rf bin/DuckHunt.out
